# Generated by Django 5.2.8 on 2025-11-16 00:33

from django.db import migrations, connection


def create_wardrobe_table(apps, schema_editor):
    """Create the wardrobe_items table using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS wardrobe_items (
                id SERIAL PRIMARY KEY,
                title TEXT,
                path TEXT,
                embedding VECTOR(512)
            );
        """)


def drop_wardrobe_table(apps, schema_editor):
    """Drop the table for rollback"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS wardrobe_items;")


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(create_wardrobe_table, drop_wardrobe_table),
    ]